'''
Created on 27 dec. 2022

@author: fmedinafernandez
'''

#LOPD LITERALS
USER_VALIDATION_LOPD_OP = 'VALIDACION DE USUARIO'
REPORTS_QUERY_LOPD_OP = 'CONSULTA DE INFORMES'
REPORTS_LABEL_LOPD_OP = 'ETIQUETADO DE INFORMES'

CORRECT_OP = 'OPERACION CORRECTA'
INCORRECT_OP = 'OPERACION INCORRECTA'
ERROR_OP = 'OPERACION EN ERROR'

#NLP CONSTANTS
FASTTEXT_MODEL = 0
TRANSFORMERS_MODEL = 1
